apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "screeps.fullname" . }}
  labels:
    {{- include "screeps.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "screeps.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "screeps.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: server
              containerPort: 21025
              protocol: TCP
          env:
            - name: SCREEPS_HOST
              value: {{ .Values.screeps.server_host }}
            - name: SCREEPS_PORT
              value: {{ .Values.screeps.server_port }}
            - name: SCREEPS_PASSWORD
              value: {{ .Values.screeps.server_password }}
            - name: STEAM_API_KEY
              value: {{ .Values.screeps.steam_api_key }}
          volumeMounts:
            - mountPath: {{ .Values.volume.mountPath }}
              name: screeps-data
      volumes:
        - name: screeps-data
          persistentVolumeClaim:
            claimName: {{ .Values.volume.claimName }}
