apiVersion: v1
kind: Service
metadata:
  name: {{ include "screeps.fullname" . }}
  labels:
    {{- include "screeps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 21025
      protocol: TCP
      name: server
  selector:
    {{- include "screeps.selectorLabels" . | nindent 4 }}
