#!/bin/bash

cd $SCREEPS_DIR

echo "Server launching... have fun ..."

mkdir -p $SCREEPS_DATABASE

echo $STEAM_API_KEY | npx screeps init
if [ ! -f $SCREEPS_DATABASE/db.json ]; then
 echo "Create empty database"
 cp -rfp $SCREEPS_DIR/db.json $SCREEPS_DATABASE/db.json
fi
npx screeps start --db $SCREEPS_DATABASE/db.json --logdir $SCREEPS_LOGS --port $SCREEPS_PORT --host $SCREEPS_HOST --password $SCREEPS_PASSWORD --cli_host $SCREEPS_CLI_HOST --cli_port $SCREEPS_CLI_PORT --steam_api_key $STEAM_API_KEY
