apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: screeps-config-data-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
