apiVersion: v1
kind: PersistentVolume
metadata:
  name: screeps-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/screeps"
